### ISSUE TITLE
Set Simulation mode off as default on main branch

### ISSUE THREAD

**Issue by mjoosbl** [thesensorpeople/leuze_rsl_ros2_drivers#3]
Hello everyone,

can you please deactivatethe simulation-mode as default on the main branch? 

`#------------------SIMULATION---------------------------
set(SIMULATION "yes")     #Set to "yes" for simulation mode` 

Thank you!

Regards,
Markus

**Comment by mrazmilan** [comment]
Good idea!
I've just set the simulation mode to "no" by default and merged into main. You can now fetch this change from the main branch.
